name: build-test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ci:
    name: go${{ matrix.go_version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.16','1.17']
        os: [ubuntu-latest]
    steps:
    - name: Use Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4
    - name: run tests
      run: |
        go test ./...